trigger:
- main
variables:
  APPNAME: "ado-dockerbuildpack"
  DOCKER_TLS_CERTDIR: ""
  TAG: "latest"
  DOCKER_HOST: tcp://docker:2375
  IMAGE_NAME: "ado"
  NAMESPACE: ""
  DOMAINNAME: ""
  DOCKER_BUILDPACK_URL: https://github.com/mendix/docker-mendix-buildpack/archive/refs/tags/v3.5.2.zip

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: build
      steps:
      - script: 
          sudo apt install curl zip unzip tar bzip2 -y; 
          wget -O buildpack.zip $(DOCKER_BUILDPACK_URL);
          unzip buildpack.zip;
          sudo mv docker-mendix-buildpack*/* . ;
          sudo docker build --build-arg BUILD_PATH=. -t $(REGISTRY_URL)/$IMAGE_NAME:$TAG . ;
          sudo docker login $(REGISTRY_URL) --username=$(REGISTRY_USER) --password=$(REGISTRY_PASSWORD);
          sudo docker push $(REGISTRY_URL)/$IMAGE_NAME:$TAG;


     
    - job: deployonK8s
      dependsOn: build
      steps:
      - script: 
         sed -i "s/{{ADMIN_PASSWORD}}/$(ADMIN_PASSWORD)/g" deployment.yaml
         sed -i "s{{DB_ENDPOINT}}$(DB_ENDPOINT)/g" deployment.yaml
         sed -i "s/{{APP_NAME}}/$(APP_NAME)/g" deployment.yaml
         sed -i "s/{{IMAGE_URL}}/${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}/g" deployment.yaml
         sed -i "s/{{DOMAINNAME}}/${DOMAINNAME}/g" deployment.yaml

    #       cat deploy.yaml
    #   - task: Kubernetes@1
    #     inputs:
    #       connectionType: 'Kubernetes Service Connection'
    #       kubernetesServiceEndpoint: 'K8s-pablo-aks'
    #       namespace: 'aks-quickstart-standalone'
    #       command: 'apply'
    #       useConfigurationFile: true
    #       configuration: 'deploy.yaml'
   
     
          
        #  kubectl apply -f deploy.yaml -n ${K8S_CLUSTER_NAMESPACE}
