trigger:
- main
variables:
  APPNAME: "ado-dockerbuildpack"
  DOCKER_TLS_CERTDIR: ""
  TAG: "latest"
  DOCKER_HOST: tcp://docker:2375
  IMAGE_NAME: "ado"
  #NAMESPACE: ""
  #DOMAINNAME: ""
  DOCKER_BUILDPACK_URL: https://github.com/mendix/docker-mendix-buildpack/archive/refs/tags/v3.5.2.zip

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
    - job: build
      steps:
      - script: 
          sudo apt install curl zip unzip tar bzip2 -y; 
          wget -O buildpack.zip $(DOCKER_BUILDPACK_URL);
          unzip buildpack.zip;
          sudo mv docker-mendix-buildpack*/* . ;
          sudo docker build --build-arg BUILD_PATH=. -t $(REGISTRY_URL)/$IMAGE_NAME:$TAG . ;
          sudo docker login $(REGISTRY_URL) --username=$(REGISTRY_USER) --password=$(REGISTRY_PASSWORD);
          sudo docker push $(REGISTRY_URL)/$IMAGE_NAME:$TAG;


     
    - job: deployonK8s
      dependsOn: build
      steps:
      - task: KubectlInstaller@0
        displayName: Kubectl installer
        inputs: 
          kubectlVersion: latest
   
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'aks-cluster'
          namespace: 'mendix-app'
          command: 'create'
          arguments: 'secret docker-registry mendix-registry-secret --docker-server=$(REGISTRY_URL) --docker-username=$(REGISTRY_USER) --docker-password=$(REGISTRY_PASSWORD)'
                  
        

      - script: 
         sed -i "s/{{ADMIN_PASSWORD}}/$(ADMIN_PASSWORD)/g" deployment.yaml;
         sed -i "s/{{DB_ENDPOINT}}/$(DB_ENDPOINT)/g" deployment.yaml;
         sed -i "s/{{APPNAME}}/$(APPNAME)/g" deployment.yaml;
         sed -i "s/{{DOMAINNAME}}/$(DOMAINNAME)/g" deployment.yaml;
         sed -i "s/{{IMAGE_URL}}/${REGISTRY_URL}\/${IMAGE_NAME}:$(TAG)/g" deployment.yaml;
         cat deployment.yaml;
  
    #   - task: Kubernetes@1
    #     inputs:
    #       connectionType: 'Kubernetes Service Connection'
    #       kubernetesServiceEndpoint: 'K8s-pablo-aks'
    #       namespace: 'aks-quickstart-standalone'
    #       command: 'apply'
    #       useConfigurationFile: true
    #       configuration: 'deploy.yaml'
   
    #  secretType: 'dockerRegistry'
    #       containerRegistryType: 'Container Registry'
    #       dockerRegistryEndpoint: 'quay-docker-registry'
    #       secretName: 'mendix-registry-secret'
          
        #  kubectl apply -f deploy.yaml -n ${K8S_CLUSTER_NAMESPACE}
