// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_Course_ScheduleTrainingEvent(IContext context, myfirstmodule.proxies.Course _course)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Course", _course == null ? null : _course.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Course_ScheduleTrainingEvent").withParams(params).execute(context);
	}
}